# Autogenerated wrapper script for libyuv_jll for aarch64-apple-darwin
export libyuv

using JpegTurbo_jll
JLLWrappers.@generate_wrapper_header("libyuv")
JLLWrappers.@declare_library_product(libyuv, "@rpath/libyuv.dylib")
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll)
    JLLWrappers.@init_library_product(
        libyuv,
        "lib/libyuv.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
