# Autogenerated wrapper script for libyuv_jll for i686-linux-musl
export libyuv

using JpegTurbo_jll
JLLWrappers.@generate_wrapper_header("libyuv")
JLLWrappers.@declare_library_product(libyuv, "libyuv.so")
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll)
    JLLWrappers.@init_library_product(
        libyuv,
        "lib/libyuv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
