# Autogenerated wrapper script for libyuv_jll for x86_64-w64-mingw32
export libyuv

using JpegTurbo_jll
JLLWrappers.@generate_wrapper_header("libyuv")
JLLWrappers.@declare_library_product(libyuv, "libyuv.dll")
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll)
    JLLWrappers.@init_library_product(
        libyuv,
        "bin\\libyuv.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
